const students = [
    {
      id: 1,
      name: "John Doe",
      subject1: 92,
      subject2: 78,
      subject3: 88,
      totalmark: 258,
    },
    {
      id: 2,
      name: "Jane Smith",
      subject1: 85,
      subject2: 90,
      subject3: 75,
      totalmark: 250,
    },
    {
      id: 3,
      name: "Alice Johnson",
      subject1: 78,
      subject2: 82,
      subject3: 94,
      totalmark: 254,
    },
    {
      id: 4,
      name: "Bob Brown",
      subject1: 89,
      subject2: 77,
      subject3: 85,
      totalmark: 251,
    },
    {
      id: 5,
      name: "Eva Davis",
      subject1: 95,
      subject2: 88,
      subject3: 90,
      totalmark: 273,
    },
    // Add more objects as needed
    {
      id: 6,
      name: "Sam Green",
      subject1: 100,
      subject2: 85,
      subject3: 79,
      totalmark: 264,
    },
    {
      id: 7,
      name: "Linda White",
      subject1: 92,
      subject2: 10,
      subject3: 88,
      totalmark: 190,
    },
    {
      id: 8,
      name: "Tom Clark",
      subject1: 76,
      subject2: 95,
      subject3: 100,
      totalmark: 271,
    },
    {
      id: 9,
      name: "Grace Adams",
      subject1: 85,
      subject2: 78,
      subject3: 92,
      totalmark: 255,
    },
    {
      id: 10,
      name: "Michael Lee",
      subject1: 94,
      subject2: 70,
      subject3: 88,
      totalmark: 252,
    },
    {
      id: 11,
      name: "Sophia Wilson",
      subject1: 90,
      subject2: 85,
      subject3: 75,
      totalmark: 250,
    },
    // Adding more users with subject1, subject2, and subject3 set to 100:
    {
      id: 12,
      name: "Olivia Turner",
      subject1: 100,
      subject2: 100,
      subject3: 100,
      totalmark: 300,
    },
    {
      id: 13,
      name: "William Harris",
      subject1: 100,
      subject2: 100,
      subject3: 100,
      totalmark: 300,
    },
    {
      id: 14,
      name: "Sophie Davis",
      subject1: 100,
      subject2: 100,
      subject3: 100,
      totalmark: 300,
    },
  ];
  module.exports = students;